"use client";
import { useEffect, useRef, useState } from "react";
import { api, type LeadDetail, type ResponseDraft } from "@/lib/api";
import { useReviewSession } from "./ReviewSession";
import ReplyComposer, { type ReviewDraft } from "./ReplyComposer";

function toReview(value: ResponseDraft): ReviewDraft { return { text: value.response_text, status: value.status === "approved" || value.status === "rejected" ? value.status : "draft" }; }
export default function PersistedReply({ detail, expanded = false, reviewHref }: { detail: LeadDetail; expanded?: boolean; reviewHref?: string }) {
  const { drafts, setDrafts } = useReviewSession();
  const id = detail.analysis.id;
  const [saved, setSaved] = useState<ResponseDraft | null>(detail.response_draft || null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const alive = useRef(true), lock = useRef(false);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const draft = drafts[id] || (saved ? toReview(saved) : { text: "", status: "draft" as const });
  function change(value: ReviewDraft) { setDrafts(previous => ({ ...previous, [id]: value })); }
  async function perform(operation: () => Promise<ResponseDraft>, message: string) {
    if (lock.current) return false;
    lock.current = true; setBusy(true); setError(""); setNotice("");
    try {
      const value = await operation();
      if (value.analysis_id !== id) throw new Error("Response draft does not match this opportunity.");
      if (!alive.current) return false;
      setSaved(value); change(toReview(value)); setNotice(message); return true;
    } catch (reason) { if (alive.current) setError(reason instanceof Error ? reason.message : "Response could not be saved."); return false; }
    finally { lock.current = false; if (alive.current) setBusy(false); }
  }
  const eligible = detail.analysis.status === "completed" && detail.analysis.is_candidate && ["review", "respond"].includes(detail.analysis.decision || "") && detail.source !== "telegram";
  return <ReplyComposer draft={draft} onChange={change} demo={false} expanded={expanded} reviewHref={reviewHref} connected={{ busy, error, notice, eligible, hasDraft: !!saved, unsaved: draft.text !== (saved?.response_text || ""), savedText: saved?.response_text || "", savedStatus: saved ? toReview(saved).status : "draft",
    generate: () => perform(() => api.generateResponse(id, !!saved), "Draft generated by the backend. Nothing was sent."),
    save: text => perform(() => api.patchResponse(id, { response_text: text, status: "edited" }), "Reply saved to the server."),
    review: status => perform(() => api.patchResponse(id, { status }), `Draft ${status} on the server. Nothing was sent.`),
  }}/>;
}
