"use client";
import { useEffect, useId, useRef, useState } from "react";
import Icon from "@/components/Icon";
import Link from "next/link";
import { textDirection } from "@/lib/lead-presentation";
import { usePreferences } from "@/components/PreferencesProvider";
export type ReviewDraft = { text: string; status: "draft" | "approved" | "rejected" };
export type ConnectedReview = { busy: boolean; activity?: string; error: string; notice: string; eligible: boolean; hasDraft: boolean; unsaved: boolean; savedText: string; savedStatus: ReviewDraft["status"]; generate: () => Promise<boolean>; save: (text: string) => Promise<boolean>; review: (status: "approved" | "rejected") => Promise<boolean> };
export default function ReplyComposer({ draft, onChange, demo, expanded = false, onGenerate, reviewHref, connected }: { draft: ReviewDraft; onChange: (draft: ReviewDraft) => void; demo: boolean; expanded?: boolean; onGenerate?: (language: "fa" | "en") => void; reviewHref?: string; connected?: ConnectedReview }) {
  const [editing, setEditing] = useState(connected ? connected.unsaved : !draft.text);
  const [notice, setNotice] = useState("");
  const [language, setLanguage] = useState<"fa" | "en">(textDirection(draft.text) === "rtl" ? "fa" : "en");
  const textarea = useRef<HTMLTextAreaElement>(null);
  const helpId = useId();
  const { preferences } = usePreferences();
  useEffect(() => { if (editing) textarea.current?.focus({ preventScroll: true }); }, [editing]);
  async function copy() {
    try { await navigator.clipboard.writeText(draft.text); setNotice(draft.status === "approved" ? "Approved reply copied." : "Draft copied."); }
    catch { setNotice("Clipboard unavailable. Use Edit to select and copy the text."); setEditing(true); }
  }
  return <section className={`reply-panel ${expanded ? "reply-expanded" : ""}`} aria-labelledby="reply-heading"><div className="reply-heading"><h2 id="reply-heading">Suggested reply</h2><span className={`badge reply-state reply-state-${draft.status}`}>{draft.status.toUpperCase()}</span>{expanded ? <select className="reply-language" aria-label="Reply language" value={language} onChange={e => { setLanguage(e.target.value as "fa" | "en"); setNotice(connected ? "Text direction selected. The API does not accept a reply language override." : "Language selected. Edit the text or restore a mock sample."); }}><option value="fa">فارسی</option><option value="en">English</option></select> : <span className="reply-language">{textDirection(draft.text) === "rtl" ? "فارسی" : "English"}</span>}{(expanded || connected) && <button className="generate-reply" type="button" disabled={connected ? connected.busy || !connected.eligible || editing || connected.unsaved : !demo || !onGenerate} title={connected ? "Generate through the backend. Nothing is sent." : demo ? "Restore a synthetic sample. No provider is called." : "Reply generation is not connected on this UI base."} onClick={() => { if (connected) { setNotice(""); void connected.generate(); return; } onGenerate?.(language); setEditing(false); setNotice("Mock sample restored locally. No provider was called."); }}><Icon name="refresh"/>{connected && !connected.hasDraft ? "Generate suggested reply" : "Generate again"}</button>}</div><p id={helpId} className="muted small">{connected ? "Save edits before approving. Approval stores your review; it does not send a message." : <>Review the wording before approving. {demo ? "Mock draft." : "Write a draft to review."} Local review only; changes are not saved to the server.</>}</p>
    <textarea ref={textarea} aria-label="Reply draft" aria-describedby={helpId} className="reply-text" dir={preferences.messageDirection !== "auto" ? preferences.messageDirection : expanded ? language === "fa" ? "rtl" : "ltr" : textDirection(draft.text)} value={draft.text} maxLength={4000} disabled={connected?.busy} readOnly={!editing} placeholder="Write a reply for human review…" onChange={event => { onChange({ text: event.target.value, status: "draft" }); setNotice(""); }}/>
    <div className="reply-editor-meta"><span>{editing ? "Editing draft" : draft.status === "approved" ? "Approved for human use" : "Draft for review"}</span><span>{draft.text.length} / 4000 characters</span></div>
    <details className="reply-preview" open={expanded || undefined}><summary>Full reply preview</summary><p dir={textDirection(draft.text)}>{draft.text || "No reply has been generated or saved."}</p></details>
    {reviewHref && <Link className="reply-expand-link" href={reviewHref}><Icon name="expand" size={15}/>Open full reply review</Link>}
    <div className="reply-actions"><button type="button" className="secondary-button" disabled={!!connected && (connected.busy || !connected.hasDraft || (editing && !draft.text.trim()))} onClick={async () => { setNotice(""); if (connected && editing) { if (await connected.save(draft.text)) setEditing(false); } else setEditing(!editing); }}><Icon name={editing ? "check" : "edit"}/>{editing ? connected ? "Save reply" : "Done editing" : "Edit"}</button>{connected && editing && <button type="button" className="secondary-button" disabled={connected.busy} onClick={() => { onChange({ text: connected.savedText, status: connected.savedStatus }); setEditing(false); }}>Cancel</button>}<button type="button" className="secondary-button" disabled={!draft.text.trim()} onClick={copy}><Icon name="copy"/>Copy</button><div className="reply-review"><button type="button" className="reject-button" disabled={!draft.text.trim() || draft.status === "rejected" || (!!connected && (connected.busy || editing || connected.unsaved || !connected.hasDraft))} onClick={() => { if (connected) { setNotice(""); void connected.review("rejected"); return; } onChange({ ...draft, status: "rejected" }); setNotice("Draft rejected locally."); }}>Reject</button><button type="button" disabled={!draft.text.trim() || draft.status === "approved" || (!!connected && (connected.busy || editing || connected.unsaved || !connected.hasDraft))} onClick={() => { if (connected) { setNotice(""); void connected.review("approved"); return; } onChange({ ...draft, status: "approved" }); setEditing(false); setNotice("Draft approved locally for your review."); }}><Icon name="check"/>Approve draft</button></div></div><p className="reply-notice" role="status">{notice || connected?.notice || "Nothing is sent automatically."}</p>
    {connected?.error && <p role="alert">{connected.error}</p>}{connected?.busy && <p role="status">{connected.activity || "Updating response…"}</p>}
  </section>;
}
