"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import Icon from "@/components/Icon";
import { usePreferences } from "@/components/PreferencesProvider";
import { useWorkspaceProducts } from "@/components/useWorkspaceProducts";
import { defaultPreferences, type Preferences } from "@/lib/preferences";
import { textDirection } from "@/lib/lead-presentation";
import "@/app/workflow.css";
import "./settings.css";
export default function SettingsPage() {
  const workspace = useWorkspaceProducts(), preference = usePreferences();
  const [draft, setDraft] = useState<Preferences>(preference.preferences), [notice, setNotice] = useState("");
  useEffect(() => { setDraft(preference.preferences); }, [preference.preferences]);
  const dirty = JSON.stringify(draft) !== JSON.stringify(preference.preferences);
  const name = workspace.demo ? "User" : workspace.user?.email.split("@")[0] || "Guest";
  function change<K extends keyof Preferences>(key: K, value: Preferences[K]) { setDraft(previous => ({ ...previous, [key]: value })); setNotice(""); }
  function save() { if (preference.save(draft)) setNotice("Preferences saved in this browser. No server settings were changed."); }
  function reset() { if (preference.reset()) { setDraft(defaultPreferences); setNotice("Preferences reset to defaults in this browser."); } }
  return <div className="settings-page"><header className="settings-title"><div><h1>Workspace settings</h1>{workspace.demo && <span className="badge">MOCK DATA</span>}</div><p>Make the workspace comfortable to read and review.</p></header>
    <div className="settings-grid"><form className="preferences-card" onSubmit={e => { e.preventDefault(); save(); }}><fieldset disabled={!preference.ready}><section><div className="settings-section-title"><span><Icon name="eye" size={27}/></span><div><h2>Appearance</h2><p>Choose how SignalX looks on this device.</p></div></div><fieldset className="theme-options"><legend>Theme</legend><div>{(["dark", "light", "system"] as const).map(theme => <label className="theme-choice" key={theme}><input type="radio" name="theme" value={theme} checked={draft.theme === theme} onChange={() => change("theme", theme)}/><span className={`theme-thumbnail theme-${theme}`} aria-hidden="true"><i className="mini-sidebar"><b/><b/><b/><b/></i><i className="mini-content"><b/><b/><b/></i>{draft.theme === theme && <span className="theme-check"><Icon name="check" size={15}/></span>}</span><span className="theme-label"><i/>{theme[0].toUpperCase() + theme.slice(1)}</span></label>)}</div></fieldset><div className="settings-row accent-row"><label htmlFor="brand-accent">Brand accent</label><div><span className="accent-swatch"/><select id="brand-accent" value="violet" onChange={() => change("accent", "violet")}><option value="violet">SignalX violet</option></select></div></div></section>
      <section className="reading-settings"><div className="settings-section-title"><span><Icon name="menu" size={26}/></span><div><h2>Reading preferences</h2><p>Adjust the reading and display experience.</p></div></div><fieldset className="settings-row density-row"><legend>Content density <small>Choose how much fits on screen.</small></legend><div className="density-options">{(["comfortable", "compact"] as const).map(value => <label key={value}><input type="radio" name="density" checked={draft.density === value} onChange={() => change("density", value)}/><span>{value[0].toUpperCase() + value.slice(1)}</span></label>)}</div></fieldset>
      <div className="settings-row"><label htmlFor="interface-language">Interface language</label><select id="interface-language" value="en" onChange={() => change("language", "en")}><option value="en">English</option></select></div><div className="settings-row"><label htmlFor="message-direction">Message direction</label><div><select id="message-direction" value={draft.messageDirection} onChange={e => change("messageDirection", e.target.value as Preferences["messageDirection"])}><option value="auto">Automatic</option><option value="ltr">Left to right</option><option value="rtl">Right to left</option></select><p className="settings-hint">Persian and English messages follow their own text direction.</p></div></div>
      <div className="settings-preview"><span>Preview</span><div>{["A clear view of every conversation.", "سلام، دنبال یک دوره پروژه‌محور هستم."].map(text => <p key={text} dir={draft.messageDirection === "auto" ? textDirection(text) : draft.messageDirection}>{text}</p>)}</div></div></section>
      <div className="preferences-actions"><button type="submit" disabled={!dirty && preference.stored}><Icon name="check"/>Save preferences</button><button className="settings-reset" type="button" onClick={reset}>Reset</button><p>Appearance preferences apply to this browser.</p></div></fieldset>{!preference.ready && <p role="status" className="settings-hint">Loading browser preferences…</p>}{notice && <p role="status" className="preferences-notice">{notice}</p>}{preference.error && <p className="preferences-error" role="alert">{preference.error}</p>}</form>
      <aside className="settings-account" aria-label="Account summary"><div className="settings-account-heading"><span className="avatar">{workspace.demo ? "U" : name[0].toUpperCase()}</span><div><h2>{name}</h2><p>{workspace.demo ? "user@signalx.io · example" : workspace.user?.email || "No connected account"}</p><span className={`workflow-status ${workspace.demo || !workspace.user ? "muted" : ""}`}>{workspace.demo ? "Demo profile · no live session" : workspace.user ? "Signed in" : "Not signed in"}</span></div></div><dl><div><dt><Icon name="home"/>Workspace</dt><dd>{workspace.demo ? "User" : "Local workspace"}</dd></div><div><dt><Icon name="product"/>Product</dt><dd>{workspace.products.find(p => p.id === workspace.selectedProductId)?.name || "Not selected"}</dd></div><div><dt><Icon name="settings"/>Mode</dt><dd>{workspace.demo ? "Mock" : "Server configured"}</dd></div></dl><button type="button" className="account-signout" disabled={workspace.signingOut || (!workspace.demo && !workspace.user)} onClick={() => void workspace.signOut()}><Icon name="arrow"/>{workspace.signingOut ? "Signing out…" : "Sign out"}</button>{workspace.demo && <p className="settings-hint">Exits the demo; no server session is ended.</p>}{workspace.accountError && <p role="alert" className="preferences-error">{workspace.accountError}</p>}{!workspace.demo && !workspace.user && <Link href="/login">Sign in</Link>}{workspace.error && <p className="settings-hint">Products unavailable: {workspace.error}</p>}</aside>
    </div></div>;
}
