"use client";
import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { api, type Analysis, type Page } from "@/lib/api";
import ErrorMessage from "@/components/ErrorMessage";
function Results() {
  const search = useSearchParams(), [run, setRun] = useState(""), [decision, setDecision] = useState(""), [minScore, setMinScore] = useState(""), [offset, setOffset] = useState(0), [data, setData] = useState<Page<Analysis> | null>(null), [error, setError] = useState<Error | null>(null), [loading, setLoading] = useState(false);
  useEffect(() => { setRun(search.get("run_id") || localStorage.getItem("run_id") || ""); }, [search]);
  useEffect(() => { if (!run) return; let cancelled = false; setLoading(true); setError(null); api.leads(run, decision, offset, minScore).then(p => { if (!cancelled) setData(p); }).catch(e => { if (!cancelled) setError(e); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [run, decision, offset, minScore]);
  return <><h1>Analysis results</h1><ErrorMessage error={error}/><div className="card"><div className="grid sm:grid-cols-3 gap-4"><div><label htmlFor="run">Run ID</label><input id="run" value={run} onChange={e => { setRun(e.target.value); setOffset(0); }}/></div><div><label htmlFor="decision">Decision</label><select id="decision" value={decision} onChange={e => { setDecision(e.target.value); setOffset(0); }}><option value="">Review + respond</option><option>respond</option><option>review</option><option>ignore</option></select></div><div><label htmlFor="min">Minimum score</label><input id="min" type="number" min="0" max="100" value={minScore} onChange={e => { setMinScore(e.target.value); setOffset(0); }}/></div></div></div>{!run ? <p>Start an analysis from Import CSV.</p> : loading ? <p>Loading results…</p> : data && <div className="card overflow-x-auto"><p>{data.total} results · Mock</p>{!data.items.length ? <p>No results match these filters. Check the run progress or choose another decision.</p> : <table className="w-full"><thead><tr><th>Score</th><th>Decision</th><th>Reason</th><th>Details</th></tr></thead><tbody>{data.items.map(a => <tr key={a.id}><td>{a.lead_score ?? "Not analyzed"}</td><td>{a.decision}</td><td>{a.reason}</td><td><Link href={`/leads/${a.id}`}>Open</Link></td></tr>)}</tbody></table>}<div className="flex gap-4 mt-4"><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 20))}>Previous</button><button disabled={offset + 20 >= data.total} onClick={() => setOffset(offset + 20)}>Next</button></div></div>}</>;
}
export default function Leads() { return <Suspense fallback={<p>Loading…</p>}><Results/></Suspense>; }
