"use client";
import Icon from "@/components/Icon";
import Link from "next/link";
import Avatar from "@/components/leads/Avatar";
import { useWorkspaceProducts } from "@/components/useWorkspaceProducts";
import { useOverview } from "@/components/workflow/useOverview";
import { demoMetadata } from "@/lib/demo-inbox";
import { DemoNotice, PageHeading, Panel, TableScroll, WorkflowLink } from "@/components/workflow/WorkflowUI";
import type { IconName } from "@/components/Icon";
import "@/app/workflow.css";
export default function DashboardPage() {
  const workspace = useWorkspaceProducts(), { demo } = workspace;
  const { run, review, counts, error, loading, retry } = useOverview(demo);
  const suffix = demo ? "?demo=1" : "";
  const leads = demo ? "/leads?demo=1" : run ? `/leads?run_id=${run.id}` : "/leads";
  const mock = run?.config_snapshot.provider_mode === "mock";
  const rows = demo && run ? [run, { ...run, id: "demo-run-023", status: "partial" as const, failed_count: 2, created_at: "2026-10-06T08:00:00Z" }, { ...run, id: "demo-run-022", total_count: 12, created_at: "2026-10-05T08:00:00Z" }] : run ? [run] : [];
  const date = demo ? "07 Oct 2026" : new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Tehran" });
  return <div className="workflow-page"><PageHeading title="Workspace overview" date={date} actions={<><WorkflowLink href={leads}><Icon name="mail" size={16}/>Open lead inbox</WorkflowLink><WorkflowLink href={`/imports${suffix}`} secondary><Icon name="plus" size={16}/>New analysis</WorkflowLink></>}><p>A clear view of conversations, decisions and feedback.</p></PageHeading>
    <div className="workflow-meta"><Icon name="file" size={18}/><strong>{run ? demo ? "Run 024" : `Run ${run.id.slice(0, 8)}` : "No run selected"}</strong>{run && <><span className={`workflow-status ${run.status === "partial" ? "amber" : ""}`}>{run.status}</span><span>{workspace.products.find(p => p.id === run.product_id)?.name || (demo ? "Backend Academy" : "Connected run")}</span></>}{demo && <span className="badge">MOCK DATA</span>}</div>
    {demo && <DemoNotice/>}
    {(error || workspace.error) && <div className="workflow-error" role="alert"><p>{error || workspace.error}</p><button className="workflow-secondary" onClick={() => { retry(); workspace.retry(); }}>Retry summary</button> <Link href="/login">Sign in</Link></div>}
    {loading && <p role="status" className="workflow-empty">Loading latest run…</p>}
    {!loading && !run && <p className="workflow-empty">Import a CSV to start your first run, or <Link href="/dashboard?demo=1">explore the demo workspace</Link>.</p>}
    <div className="overview-metrics">{[[run?.processed_count ?? "—", "Messages analyzed", "chat"], [counts ? counts[0] + counts[1] : "—", "Relevant opportunities", "leads"], [demo ? 3 : "—", "Approved drafts", "check"], [mock ? "$0.00" : "—", mock ? "Mock run cost" : "Run cost unavailable", "product"]].map(([value, label, icon]) => <div className="overview-metric" key={label}><Icon name={icon as IconName} size={31}/><div><strong>{value}</strong><span>{label}</span></div></div>)}</div>
    <div className="overview-columns"><Panel title="Decision overview"><p className="panel-description">How the latest run&apos;s messages were classified.</p><div className="decision-summary">{[["Respond", "Ready for a thoughtful reply", "respond"], ["Review", "Needs a closer look", "review"], ["Skip", "Outside the product profile", "ban"]].map(([label, hint, icon], i) => <Link href={leads} key={label}><span className="decision-icon"><Icon name={icon as IconName} size={28}/></span><div><strong>{label}</strong><small>{hint}</small></div><b>{counts?.[i] ?? "—"}</b><Icon name="chevron" size={17}/></Link>)}</div><div className="review-heading"><h3>Next to review</h3><span>{review.length} conversations</span></div><ul className="review-list">{review.map((detail, i) => <li key={detail.analysis.id}><Link href={demo ? leads : `/leads/${detail.analysis.id}`}><div className="workflow-person"><Avatar name={detail.message.author} index={i + 4}/><div><strong>{detail.message.author}</strong><small>{demo ? demoMetadata[detail.analysis.id]?.community : "Imported community"}</small></div></div><b>{detail.analysis.lead_score ?? "—"}</b><span className="workflow-status amber">Review</span><Icon name="chevron" size={15}/></Link></li>)}</ul>{!review.length && <p className="workflow-empty">{loading ? "Loading review queue…" : "No conversations to review."}</p>}</Panel>
    <Panel title="Reply feedback" className="overview-feedback"><p className="panel-description">Quality of reviewed drafts in the latest run.</p><div className="feedback-ratio"><strong>{demo ? 3 : "—"}</strong><span>/</span>{demo ? 4 : "—"}</div><p className="feedback-caption">reviewed drafts approved</p><div className="feedback-totals"><div><Icon name="check" size={19}/><b>{demo ? 3 : "—"}</b><span>Approved</span></div><div><Icon name="close" size={19}/><b>{demo ? 1 : "—"}</b><span>Rejected</span></div></div><p className="panel-description">{demo ? "Based on 4 synthetic reviewed drafts." : "Feedback API is not connected on this UI base."}</p><div className="feedback-sample"><h3>Latest feedback</h3>{demo ? <><div className="workflow-person"><Avatar name="Alex" index={1}/><div><strong>Alex</strong><small>DevTalk</small></div><span className="feedback-tag">Needs more context</span></div><p>“Make the reply more specific to the question.”</p></> : <p className="workflow-empty">No persisted feedback available.</p>}</div><div className="feedback-cost"><Icon name="product" size={22}/><strong>{mock ? "$0.00" : "—"}</strong><span>{mock ? "provider cost · Mock run" : "Provider cost unavailable"}</span></div></Panel></div>
    <Panel title="Recent runs" className="recent-runs" extra={<span>{demo ? "Latest example analysis runs in this workspace." : "Latest selected run · history API not available."}</span>}><TableScroll label="Recent analysis runs"><table><thead><tr>{["Run", "Date", "Messages", "Status", "Cost", ""].map((h, i) => <th scope="col" key={i}>{h || <span className="sr-only">Open run</span>}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={r.id}><td>{demo ? `Run ${String(24 - i).padStart(3, "0")}` : r.id.slice(0, 8)}</td><td>{new Date(r.created_at).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}</td><td>{r.total_count}</td><td><span className={`workflow-status ${r.status === "partial" ? "amber" : ""}`}>{r.status}{r.failed_count ? ` · ${r.failed_count} failed` : ""}</span></td><td>{r.config_snapshot.provider_mode === "mock" ? "$0.00" : "—"}</td><td><Link href={`/runs/${r.id}${suffix}`} aria-label={`Open ${demo ? `Run ${24 - i}` : r.id}`}><Icon name="chevron" size={16}/></Link></td></tr>)}</tbody></table></TableScroll>{!rows.length && <p className="workflow-empty">No runs yet.</p>}</Panel>
  </div>;
}
